//lint:file-ignore ST1005 Generated code

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	zalandoorgv1 "github.com/szuecs/routegroup-client/apis/zalando.org/v1"
	scheme "github.com/szuecs/routegroup-client/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RouteGroupsGetter has a method to return a RouteGroupInterface.
// A group's client should implement this interface.
type RouteGroupsGetter interface {
	RouteGroups(namespace string) RouteGroupInterface
}

// RouteGroupInterface has methods to work with RouteGroup resources.
type RouteGroupInterface interface {
	Create(ctx context.Context, routeGroup *zalandoorgv1.RouteGroup, opts metav1.CreateOptions) (*zalandoorgv1.RouteGroup, error)
	Update(ctx context.Context, routeGroup *zalandoorgv1.RouteGroup, opts metav1.UpdateOptions) (*zalandoorgv1.RouteGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, routeGroup *zalandoorgv1.RouteGroup, opts metav1.UpdateOptions) (*zalandoorgv1.RouteGroup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*zalandoorgv1.RouteGroup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*zalandoorgv1.RouteGroupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *zalandoorgv1.RouteGroup, err error)
	RouteGroupExpansion
}

// routeGroups implements RouteGroupInterface
type routeGroups struct {
	*gentype.ClientWithList[*zalandoorgv1.RouteGroup, *zalandoorgv1.RouteGroupList]
}

// newRouteGroups returns a RouteGroups
func newRouteGroups(c *ZalandoV1Client, namespace string) *routeGroups {
	return &routeGroups{
		gentype.NewClientWithList[*zalandoorgv1.RouteGroup, *zalandoorgv1.RouteGroupList](
			"routegroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *zalandoorgv1.RouteGroup { return &zalandoorgv1.RouteGroup{} },
			func() *zalandoorgv1.RouteGroupList { return &zalandoorgv1.RouteGroupList{} },
		),
	}
}
