//lint:file-ignore ST1005 Generated code

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/szuecs/routegroup-client/apis/zalando.org/v1"
	"github.com/szuecs/routegroup-client/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ZalandoV1Interface interface {
	RESTClient() rest.Interface
	RouteGroupsGetter
}

// ZalandoV1Client is used to interact with features provided by the zalando.org group.
type ZalandoV1Client struct {
	restClient rest.Interface
}

func (c *ZalandoV1Client) RouteGroups(namespace string) RouteGroupInterface {
	return newRouteGroups(c, namespace)
}

// NewForConfig creates a new ZalandoV1Client for the given config.
func NewForConfig(c *rest.Config) (*ZalandoV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ZalandoV1Client{client}, nil
}

// NewForConfigOrDie creates a new ZalandoV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ZalandoV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ZalandoV1Client for the given RESTClient.
func New(c rest.Interface) *ZalandoV1Client {
	return &ZalandoV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ZalandoV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
