//lint:file-ignore ST1005 Generated code

// Code generated by lister-gen. DO NOT EDIT.

package v1

// RouteGroupListerExpansion allows custom methods to be added to
// RouteGroupLister.
type RouteGroupListerExpansion interface{}

// RouteGroupNamespaceListerExpansion allows custom methods to be added to
// RouteGroupNamespaceLister.
type RouteGroupNamespaceListerExpansion interface{}
