//lint:file-ignore ST1005 Generated code

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	zalandoorgv1 "github.com/szuecs/routegroup-client/apis/zalando.org/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RouteGroupLister helps list RouteGroups.
// All objects returned here must be treated as read-only.
type RouteGroupLister interface {
	// List lists all RouteGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*zalandoorgv1.RouteGroup, err error)
	// RouteGroups returns an object that can list and get RouteGroups.
	RouteGroups(namespace string) RouteGroupNamespaceLister
	RouteGroupListerExpansion
}

// routeGroupLister implements the RouteGroupLister interface.
type routeGroupLister struct {
	listers.ResourceIndexer[*zalandoorgv1.RouteGroup]
}

// NewRouteGroupLister returns a new RouteGroupLister.
func NewRouteGroupLister(indexer cache.Indexer) RouteGroupLister {
	return &routeGroupLister{listers.New[*zalandoorgv1.RouteGroup](indexer, zalandoorgv1.Resource("routegroup"))}
}

// RouteGroups returns an object that can list and get RouteGroups.
func (s *routeGroupLister) RouteGroups(namespace string) RouteGroupNamespaceLister {
	return routeGroupNamespaceLister{listers.NewNamespaced[*zalandoorgv1.RouteGroup](s.ResourceIndexer, namespace)}
}

// RouteGroupNamespaceLister helps list and get RouteGroups.
// All objects returned here must be treated as read-only.
type RouteGroupNamespaceLister interface {
	// List lists all RouteGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*zalandoorgv1.RouteGroup, err error)
	// Get retrieves the RouteGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*zalandoorgv1.RouteGroup, error)
	RouteGroupNamespaceListerExpansion
}

// routeGroupNamespaceLister implements the RouteGroupNamespaceLister
// interface.
type routeGroupNamespaceLister struct {
	listers.ResourceIndexer[*zalandoorgv1.RouteGroup]
}
