//lint:file-ignore ST1005 Generated code

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/szuecs/routegroup-client/apis/zalando.org/v1"
	zalandoorgv1 "github.com/szuecs/routegroup-client/client/clientset/versioned/typed/zalando.org/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRouteGroups implements RouteGroupInterface
type fakeRouteGroups struct {
	*gentype.FakeClientWithList[*v1.RouteGroup, *v1.RouteGroupList]
	Fake *FakeZalandoV1
}

func newFakeRouteGroups(fake *FakeZalandoV1, namespace string) zalandoorgv1.RouteGroupInterface {
	return &fakeRouteGroups{
		gentype.NewFakeClientWithList[*v1.RouteGroup, *v1.RouteGroupList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("routegroups"),
			v1.SchemeGroupVersion.WithKind("RouteGroup"),
			func() *v1.RouteGroup { return &v1.RouteGroup{} },
			func() *v1.RouteGroupList { return &v1.RouteGroupList{} },
			func(dst, src *v1.RouteGroupList) { dst.ListMeta = src.ListMeta },
			func(list *v1.RouteGroupList) []*v1.RouteGroup { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.RouteGroupList, items []*v1.RouteGroup) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
