//lint:file-ignore ST1005 Generated code

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiszalandoorgv1 "github.com/szuecs/routegroup-client/apis/zalando.org/v1"
	versioned "github.com/szuecs/routegroup-client/client/clientset/versioned"
	internalinterfaces "github.com/szuecs/routegroup-client/client/informers/externalversions/internalinterfaces"
	zalandoorgv1 "github.com/szuecs/routegroup-client/client/listers/zalando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RouteGroupInformer provides access to a shared informer and lister for
// RouteGroups.
type RouteGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() zalandoorgv1.RouteGroupLister
}

type routeGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRouteGroupInformer constructs a new informer for RouteGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRouteGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRouteGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRouteGroupInformer constructs a new informer for RouteGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRouteGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZalandoV1().RouteGroups(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZalandoV1().RouteGroups(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZalandoV1().RouteGroups(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZalandoV1().RouteGroups(namespace).Watch(ctx, options)
			},
		}, client),
		&apiszalandoorgv1.RouteGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *routeGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRouteGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *routeGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiszalandoorgv1.RouteGroup{}, f.defaultInformer)
}

func (f *routeGroupInformer) Lister() zalandoorgv1.RouteGroupLister {
	return zalandoorgv1.NewRouteGroupLister(f.Informer().GetIndexer())
}
