//lint:file-ignore ST1005 Generated code

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/szuecs/routegroup-client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// RouteGroups returns a RouteGroupInformer.
	RouteGroups() RouteGroupInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// RouteGroups returns a RouteGroupInformer.
func (v *version) RouteGroups() RouteGroupInformer {
	return &routeGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
