// +build !ignore_autogenerated

//lint:file-ignore ST1005 Generated code

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroup) DeepCopyInto(out *RouteGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroup.
func (in *RouteGroup) DeepCopy() *RouteGroup {
	if in == nil {
		return nil
	}
	out := new(RouteGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RouteGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupBackend) DeepCopyInto(out *RouteGroupBackend) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupBackend.
func (in *RouteGroupBackend) DeepCopy() *RouteGroupBackend {
	if in == nil {
		return nil
	}
	out := new(RouteGroupBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupBackendReference) DeepCopyInto(out *RouteGroupBackendReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupBackendReference.
func (in *RouteGroupBackendReference) DeepCopy() *RouteGroupBackendReference {
	if in == nil {
		return nil
	}
	out := new(RouteGroupBackendReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupList) DeepCopyInto(out *RouteGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RouteGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupList.
func (in *RouteGroupList) DeepCopy() *RouteGroupList {
	if in == nil {
		return nil
	}
	out := new(RouteGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RouteGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupLoadBalancer) DeepCopyInto(out *RouteGroupLoadBalancer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupLoadBalancer.
func (in *RouteGroupLoadBalancer) DeepCopy() *RouteGroupLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(RouteGroupLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupLoadBalancerStatus) DeepCopyInto(out *RouteGroupLoadBalancerStatus) {
	*out = *in
	if in.RouteGroup != nil {
		in, out := &in.RouteGroup, &out.RouteGroup
		*out = make([]RouteGroupLoadBalancer, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupLoadBalancerStatus.
func (in *RouteGroupLoadBalancerStatus) DeepCopy() *RouteGroupLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(RouteGroupLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupRouteSpec) DeepCopyInto(out *RouteGroupRouteSpec) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]RouteGroupBackendReference, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupRouteSpec.
func (in *RouteGroupRouteSpec) DeepCopy() *RouteGroupRouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteGroupRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupSpec) DeepCopyInto(out *RouteGroupSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]RouteGroupBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultBackends != nil {
		in, out := &in.DefaultBackends, &out.DefaultBackends
		*out = make([]RouteGroupBackendReference, len(*in))
		copy(*out, *in)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteGroupRouteSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupSpec.
func (in *RouteGroupSpec) DeepCopy() *RouteGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RouteGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteGroupStatus) DeepCopyInto(out *RouteGroupStatus) {
	*out = *in
	in.LoadBalancer.DeepCopyInto(&out.LoadBalancer)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteGroupStatus.
func (in *RouteGroupStatus) DeepCopy() *RouteGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RouteGroupStatus)
	in.DeepCopyInto(out)
	return out
}
